name: curve25519
version: 1.0.0
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/curve25519
description: Implements X25519 key exchange (elliptic curve Diffie-Hellman over Curve25519).

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ^1.0.0
  pedantic: ^1.0.0
  raw: ^0.2.0
  test: ^1.4.0
